# Jeux de données 
# https://www.data.gouv.fr/datasets/trafic-aerien-commercial-mensuel-francais-par-paire-daeroports-par-sens-depuis-1990/

airports: "https://www.data.gouv.fr/api/1/datasets/r/ad91ede7-3eb9-41fe-8a00-0324210bfa59"

liaisons: "https://www.data.gouv.fr/api/1/datasets/r/c89f2fb5-df1f-4a53-adf5-27f719e44137"

compagnies: "https://www.data.gouv.fr/api/1/datasets/r/78daf539-0793-4e59-b3bb-202c4246f3c7"

geojson:
  airport: "https://minio.lab.sspcloud.fr/projet-funathon/2024/sujet2/aeroports.geojson"

