FROM inseefrlab/onyxia-jupyter-python:py3.13.12

# Add files necessary for the running app
ADD correction/app.py .
ADD correction/sources.yml .
ADD pyproject.toml .

# Move directories to the project root
COPY correction/src src/
COPY correction/.streamlit .streamlit/


# Install dependencies
RUN uv sync

EXPOSE 8000
CMD ["uv", "run", "streamlit", "run", "app.py", "--server.port=8000", "--server.address=0.0.0.0"]
